# Generated by Django 4.0.3 on 2022-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
