# Generated by Django 4.0.3 on 2022-04-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinflar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinf_1',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-1'),
        ),
        migrations.AddField(
            model_name='sinf_1',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
