# Generated by Django 4.0.3 on 2022-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinflar', '0002_sinf_1_image_sinf_1_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
        migrations.CreateModel(
            name='Sinf_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familya', models.CharField(max_length=100, null=True)),
                ('sharif', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='sinf-1')),
            ],
        ),
    ]
