# Generated by Django 4.0.3 on 2022-04-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinflar', '0003_sinf_10_sinf_11_sinf_2_sinf_3_sinf_4_sinf_5_sinf_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinf_10',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-10'),
        ),
        migrations.AlterField(
            model_name='sinf_11',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-11'),
        ),
        migrations.AlterField(
            model_name='sinf_2',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-2'),
        ),
        migrations.AlterField(
            model_name='sinf_3',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-3'),
        ),
        migrations.AlterField(
            model_name='sinf_4',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-4'),
        ),
        migrations.AlterField(
            model_name='sinf_5',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-5'),
        ),
        migrations.AlterField(
            model_name='sinf_6',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-6'),
        ),
        migrations.AlterField(
            model_name='sinf_7',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-7'),
        ),
        migrations.AlterField(
            model_name='sinf_8',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-8'),
        ),
        migrations.AlterField(
            model_name='sinf_9',
            name='image',
            field=models.ImageField(null=True, upload_to='sinf-9'),
        ),
    ]
